name: Service CI/CD Workflow
on:
  push:
    branches: main
    paths:
      - hm-service/
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: hm-service
