name: Service CI Workflow
on:
  push:
    branches: [ main ]
    paths:
      - hm-service/
  pull_request:
    branches: [ main ]
    paths:
      - hm-service/

jobs:
  build:
    runs-on: ubuntu-latest
    environment: hm-service
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle Build
      working-directory: ./hm-service
      run: ./gradlew bootJar
