name: Web CI/CD Workflow
on:
  push:
    branches: [ main ]
    paths:
      - hm-web/
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: hm-ui
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      working-directory: ./hm-web
      with:
        node-version: 14.x
        cache: 'npm'

    - name: build
      working-directory: ./hm-web
      env:
        REACT_APP_API_URL : ${{ secrets.API_URL }}
      run: |
        npm install
        CI=false npm run build

    - name: Upload to S3
      working-directory: ./hm-web
      if: startsWith(github.ref, 'refs/tags/v') && (github.event.pull_request.merged == 'true' || github.event_name == 'push')
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
      run: |
        aws s3 sync ./build/static "s3://$BUCKET_NAME/static" --cache-control max-age=3156000
        aws s3 sync ./build/ "s3://$BUCKET_NAME" --exclude "static/*" --cache-control no-cache
        aws cloudfront create-invalidation \
          --distribution-id "$DISTRIBUTION_ID" \
          --paths '/*' \
          --query Invalidation.Id \
          --output text
